### ISSUE TITLE
Module parse failed: Unexpected token (7:6)

### ISSUE THREAD

**Issue by psnehanshu** [sindresorhus/yocto-queue#3]
This issue came up when trying to use the [p-settle](https://github.com/sindresorhus/p-settle) library. I am trying to use it on a Vue.js project.

![image](https://user-images.githubusercontent.com/9392350/146352488-dc23c06d-9a88-4429-970b-595dac1594f1.png)

I am using Node v16.13.1 and NPM v6.14.15.

**Comment by sindresorhus** [comment]
This is a problem with your bundler not supporting modern JS syntax, not this package.

**Comment by cwoolum** [comment]
This just started occurring for us yesterday as well... I'm guessing there is a breaking change somewhere in the CRA stack.

**Comment by MagnesiumDev** [comment]
It's happening to me as well, @cwoolum have you found a solution?

**Comment by MagnesiumDev** [comment]
Updated react-scripts and now  it works like a charm ✌️

**Comment by 3xau1o** [comment]
i also faced this problem on webpack 4 and 5
