### ISSUE TITLE
Compatible with Safari

### ISSUE THREAD

**Issue by skysbird** [sindresorhus/yocto-queue#4]
Safari will complain about "SyntaxError: Invalid character: '#'"

![image](https://user-images.githubusercontent.com/38487/198947857-3b51dc43-5991-49f3-b711-f81ffe89fb61.png)

**Comment by sindresorhus** [comment]
This package uses any syntax available in Node.js 12: https://github.com/sindresorhus/yocto-queue/blob/7fafbd82adbba0d479e9dd644db480506f1c7ee1/package.json#L16

It's up to you to transpile with Babel if you need to support browsers that does not support such syntax.
